name: Python App CI/CD Pipeline with Direct Deployment

on:
  push:
    branches:
      - stage-6

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: |
        pip install -r requirements.txt

    # Run tests
    - name: Run tests
      run: |
        echo "Run tests"

    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure Webapp Update
      run: |
        az vmss extension set \
          --resource-group ${{ secrets.WEEK4_RESOURCE_GROUP }} \
          --vmss-name ${{ secrets.WEEK4_VMSS_NAME }} \
          --name CustomScript \
          --force-update \
          --publisher Microsoft.Azure.Extensions \
          --settings '{"commandToExecute": "/home/azureuser/SDA-bootcamp-project/update_app.sh"}'